### ISSUE TITLE
Hiatus?

### ISSUE THREAD

**Issue by EnzoMartin** [AzemOcram/OcramTower#5]
Out of curiosity, is this project on hiatus?

**Comment by AzemOcram** [comment]
Anyone can work on it if they so wish. I, the project's owner and main contributor, am rather busy. I moved to go to a good university and pursue a bachelor's degree completely unrelated to games and programming.

**Comment by EnzoMartin** [comment]
Fair enough, you wouldn't have the source files you'd be willing to upload of the sprites you made per chance?

I've been building my own version in React in my spare time, but I suck at graphics, so I'm using colored boxes currently. Granted, I'm not anywhere near the point where graphics matter at all (I have placing/deleteing/moving/basic stuff), but just for future potential use (with attribution of course)
